Cyber-Main/JSL_Threat_Intel_Framework/phase3_geowhois/WhoDat/pydat/pydat/urls.py
from django.conf.urls import patterns, url
from django.conf import settings

urlpatterns = patterns('',
                       url(r'^$', 'pydat.views.index', name='index'),

                       url(r'^domains/(?P<key>.*)/(?P<value>.*)/$', 'pydat.views.domains'),
                       url(r'^domains/$', 'pydat.views.domains', name='domains'),

                       url(r'^pdns_results/(?P<domain>.*)/$', 'pydat.views.pdns', name='pdns_rest'),
                       url(r'^pdns_results/$', 'pydat.views.pdns', name='pdns_results'),
                       url(r'^pdns_search/$', 'pydat.views.pdns_index', name='pdns'),

                       url(r'^pdnsr_results/(?P<key>.*)/(?P<value>.*)/$', 'pydat.views.pdns_r', name='pdns_r_rest'),
                       url(r'^pdnsr_results/$', 'pydat.views.pdns_r', name='pdns_r_results'),
                       url(r'^pdnsr_search/$', 'pydat.views.rpdns_index', name='pdns_r'),

                       url(r'^ajax/metadata/$', 'pydat.ajax.metadata'),
                       url(r'^ajax/metadata/(?P<version>.*)/$', 'pydat.ajax.metadata'),

                       url(r'^ajax/domain/(?P<domainName>.*)/diff/(?P<v1>.*)/(?P<v2>.*)/$', 'pydat.ajax.domain_diff'),
                       url(r'^ajax/domain/(?P<domainName>.*)/(?P<low>.*)/(?P<high>.*)/$', 'pydat.ajax.domain'),
                       url(r'^ajax/domain/(?P<domainName>.*)/latest/$', 'pydat.ajax.domain_latest'),
                       url(r'^ajax/domain/(?P<domainName>.*)/(?P<low>.*)/$', 'pydat.ajax.domain'),
                       url(r'^ajax/domain/(?P<domainName>.*)/$', 'pydat.ajax.domain'),
                       url(r'^ajax/domain/$', 'pydat.ajax.domain', name='ajax_domain'),

                       url(r'^ajax/domains/(?P<key>.*)/(?P<value>.*)/(?P<low>.*)/(?P<high>.*)/$', 'pydat.ajax.domains'),
                       url(r'^ajax/domains/(?P<key>.*)/(?P<value>.*)/latest/$', 'pydat.ajax.domains_latest'),
                       url(r'^ajax/domains/(?P<key>.*)/(?P<value>.*)/(?P<low>.*)/$', 'pydat.ajax.domains'),
                       url(r'^ajax/domains/(?P<key>.*)/(?P<value>.*)/$', 'pydat.ajax.domains'),
                       url(r'^ajax/domains/$', 'pydat.ajax.domains', name='ajax_domains'),

                       url(r'^ajax/dataTable/(?P<key>.*)/(?P<value>.*)/(?P<low>.*)/(?P<high>.*)/$',
                           'pydat.ajax.dataTable'),
                       url(r'^ajax/dataTable/$', 'pydat.ajax.dataTable', name='ajax_dataTable'),

                       url(r'^ajax/resolve/(?P<domainName>.*)/$', 'pydat.ajax.resolve'),
                       url(r'^ajax/resolve/$', 'pydat.ajax.resolve', name='ajax_resolve'),
                       )

if settings.HANDLER == 'es':  # Enable ES specific urls
    urlpatterns += patterns('',
                            url(r'^advdomains/$', 'pydat.views.advdomains', name='advdomains'),
                            url(r'^ajax/query/$', 'pydat.ajax.advanced_search', name='ajax_advanced'),
                            url(r'^ajax/advDataTable/$', 'pydat.ajax.advDataTable', name='ajax_advDataTable'),
                            url(r'^stats/$', 'pydat.views.stats', name='stats'),
                            url(r'^help/$', 'pydat.views.help', name='help'),
                            )

Cyber-Main/JSL_Threat_Intel_Framework/phase3_geowhois/WhoDat/pydat/pydat/forms.py
import socket
from django import forms
from django.conf import settings
from pydat.handlers import handler
import urllib


class domain_form(forms.Form):
    key = forms.ChoiceField(label="Key")
    value = forms.CharField(label="Value")
    latest = forms.BooleanField(label="Latest", initial=False, required=False)
    filt = forms.ChoiceField(label="Filter")
    fmt = forms.ChoiceField(label="Format")
    limit = forms.IntegerField(label="Limit", min_value=1,
                               max_value=settings.LIMIT,
                               initial=settings.LIMIT)

    def __init__(self, *args, **kwargs):
        super(domain_form, self).__init__(*args, **kwargs)
        self.fields['key'].choices = settings.SEARCH_KEYS
        self.fields['fmt'].choices = [('normal', 'Web'),
                                      ('json', 'JSON'),
                                      ('list', 'List')]
        nonelist = [('none', 'None')]
        nonelist.extend(settings.SEARCH_KEYS)

        self.fields['filt'].choices = settings.SEARCH_KEYS

        for field in self.fields.values():
            field.error_messages = {'required': '%s is required' % field.label,
                                    'invalid_choice': '%s is invalid' % field.label}

    def clean_latest(self):
        if 'latest' not in self.cleaned_data or self.cleaned_data['latest'] is None:
            return False
        else:
            return self.cleaned_data['latest']

    def clean_value(self):
        value = self.cleaned_data['value']
        if 'key' in self.cleaned_data:
            key = self.cleaned_data['key']
            if key == 'domainName':  # Support Internationalization
                if isinstance(value, unicode):
                    value = value.encode("idna")
                return value
        return value


class advdomain_form(forms.Form):
    query = forms.CharField(label='Search', widget=forms.TextInput(attrs={'size': '60'}))
    filt = forms.ChoiceField(label="Filter", required=False)
    fmt = forms.ChoiceField(label="Format", required=False)
    limit = forms.IntegerField(label="Limit", min_value=1,
                               max_value=settings.LIMIT,
                               initial=settings.LIMIT,
                               required=False)
    unique = forms.BooleanField(label="Unique", initial=False, required=False)

    def __init__(self, *args, **kwargs):
        super(advdomain_form, self).__init__(*args, **kwargs)
        self.fields['fmt'].choices = [('normal', 'Web'),
                                      ('json', 'JSON'),
                                      ('list', 'List')]
        nonelist = [('none', 'None')]
        nonelist.extend(settings.SEARCH_KEYS)

        self.fields['filt'].choices = settings.SEARCH_KEYS

        for field in self.fields.values():
            field.error_messages = {'required': '%s is required' % field.label,
                                    'invalid_choice': '%s is invalid' % field.label}

    def clean_unique(self):
        if 'unique' not in self.cleaned_data or self.cleaned_data['unique'] is None:
            return False
        else:
            return self.cleaned_data['unique']

    def clean_query(self):
        if 'query' not in self.cleaned_data:
            raise forms.ValidationError("query field required")
        try:
            query = urllib.unquote(self.cleaned_data['query'])
        except:
            raise forms.ValidationError("Unable to unquote query")
        result = handler.test_query(query)
        if result is not None:
            raise forms.ValidationError("Unable to parse query: %s" % result)
        return query


# Allows you to provide a drop down of numbers but support non listed number
class ChoiceNumberField(forms.ChoiceField):
    minimum = 0
    maximum = 0

    def __init__(self, *args, **kwargs):
        if kwargs is not None:
            if 'maximum' in kwargs:
                self.maximum = kwargs['maximum']
                del kwargs['maximum']
            if 'minimum' in kwargs:
                self.minimum = kwargs['minimum']
                del kwargs['minimum']

        super(ChoiceNumberField, self).__init__(*args, **kwargs)

    def validate(self, value):
        try:
            value = int(value)
            if self.maximum > 0 and value > self.maximum:
                raise forms.ValidationError("Value too large")
            if value < self.minimum:
                raise forms.ValidationError("Value too small")
            return value
        except Exception, e:
            raise forms.ValidationError("Unable to process number")


class pdns_super(forms.Form):
    fmt = forms.ChoiceField(label="Format")
    limit = ChoiceNumberField(label="Limit", maximum=settings.DNSDB_LIMIT, minimum=1)
    absolute = forms.BooleanField(label="Absolute", initial=False, required=False)
    pretty = forms.BooleanField(label='Pretty', initial=True, required=False)
    filt = forms.ChoiceField(label="Filter")
    rrtypes = forms.MultipleChoiceField(label="RR Types",
                                        widget=forms.SelectMultiple)

    def __init__(self, *args, **kwargs):
        super(pdns_super, self).__init__(*args, **kwargs)
        self.fields['fmt'].choices = [('normal', 'Web'),
                                      ('json', 'JSON'),
                                      ('list', 'List')]
        self.fields['limit'].choices = [(val, val) for val in settings.DNSDB_PAGE_LIMITS]
        self.initial['limit'] = settings.DNSDB_PAGE_LIMITS[settings.DNSDB_PAGE_LIMIT_DEFAULT]

        self.fields['filt'].choices = [('rrname', 'RRName'),
                                       ('rdata', 'RData')]

        self.fields['rrtypes'].choices = settings.RRTYPE_KEYS
        self.initial['rrtypes'] = [settings.RRTYPE_KEYS[0][0]]

        for field in self.fields.values():
            field.error_messages = {'required': '%s is required' % field.label,
                                    'invalid_choice': '%s is invalid' % field.label}

    def clean_absolute(self):
        if 'absolute' not in self.cleaned_data or self.cleaned_data['absolute'] is None:
            return False
        else:
            return self.cleaned_data['absolute']

    def clean_pretty(self):
        if 'pretty' not in self.cleaned_data or self.cleaned_data['pretty'] is None:
            return True
        else:
            return self.cleaned_data['pretty']

    def clean_limit(self):
        limit = int(self.cleaned_data['limit'])
        if limit < 1:
            raise forms.ValidationError("Limit too small")
        elif limit > settings.DNSDB_LIMIT:
            raise forms.ValidationError("Limit too large")
        return limit


class pdns_form(pdns_super):
    domain = forms.CharField(label="Domain")

    def __init__(self, *args, **kwargs):
        super(pdns_form, self).__init__(*args, **kwargs)

    def clean_domain(self):
        domain = self.cleaned_data['domain']
        if isinstance(domain, unicode):
            domain = domain.encode("idna")
            return domain
        return domain


class pdns_r_form(pdns_super):
    key = forms.ChoiceField(label="Type")
    value = forms.CharField(label="Query")

    def __init__(self, *args, **kwargs):
        super(pdns_r_form, self).__init__(*args, **kwargs)
        self.fields['key'].choices = settings.RDATA_KEYS

    def clean_value(self):
        if 'key' not in self.cleaned_data:
            raise forms.ValidationError('Unable to parse query')

        key = self.cleaned_data['key']
        value = self.cleaned_data['value']
        if key == "ip":
            (status, output) = validate_ip(value)
            if not status:
                raise forms.ValidationError(output)
            value = output
        elif key == "raw":
            output = validate_hex(value)
            if output is None:
                raise forms.ValidationError("Invalid Hex")
            value = output
        elif key == "name":
            if isinstance(value, unicode):
                value = value.encode("idna")
        return value


def validate_ip(input_ip):
    ip = ""
    mask = None
    version = 4
    if input_ip.count("/") > 0:
        if input_ip.count("/") > 1:
            return (False, "Invalid IP Syntax")
        (ip, mask) = input_ip.split("/")
    else:
        ip = input_ip

    # Validate ip part
    try:
        socket.inet_pton(socket.AF_INET6, ip)
        version = 6
    except:  # invalid ipv6
        try:
            socket.inet_pton(socket.AF_INET, ip)
        except Exception, e:
            return (False, "Invalid IP Address")

    output_ip = ip
    # Validate mask if present
    if mask is not None:
        try:
            mask = int(mask)
            if mask < 1:
                return (False, "Mask must be at least 1")
            elif version == 4 and mask > 32:
                return (False, "IP Mask too large for v4")
            elif version == 6 and mask > 128:
                return (False, "IP Mask too large for v6")
        except:
            return (False, "Unable to process mask")
        output_ip += ",%d" % mask
    return (True, output_ip)


def validate_hex(input_hex):
    try:
        output_hex = "%x" % int(input_hex, 16)
    except:
        return None
    if len(output_hex) % 2 == 1:  # make hex string always pairs of hex values
        output_hex = "0" + output_hex

    return output_hex

Cyber-Main/JSL_Threat_Intel_Framework/phase3_geowhois/WhoDat/pydat/pydat/templates/base.html
<!DOCTYPE HTML>
<html>
<head>
    <title>pyDat: {% block title %}WHOIS exploration{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}/css/jquery-ui-1.10.4.css">
    <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}/css/jquery.dataTables.css">
    <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}/css/pydat.css">
    {% block css %}
    {% endblock %}
    <script type="text/javascript" src="{{STATIC_URL}}/js/jquery-1.11.0.min.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}/js/jquery-ui-1.10.4.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}/js/jquery.dataTables.js"></script>
    <script type="text/javascript">
          var resolve_url = "{% url 'ajax_resolve' %}";
          var csrf_token = '{{ csrf_token }}';
          var latest_version = '{{ latest_version }}';



    </script>
    {% block js_constants %}
    {% endblock %}
    <script type="text/javascript" src="{{STATIC_URL}}/js/pydat.js"></script>
    {% block js %}
    {% endblock %}
</head>
<body>
<div id="bodywrapper">
    <div id="header">
        {% include 'navigation_bar.html' %}
        <div class='clear'>
        </div>
        <div id="searchIcon">
            <span id="button" class="ui-icon ui-icon-minus"></span>
        </div>
        <div class='clear'>
        </div>

        <div id='searchBar'>
            <div id='search'>
                {% block searchBar %}
                {% endblock %}
            </div>
            {% if handler == 'es' %}
            {% include 'status_part.html' %}
            {% endif %}
        </div><!-- searchBar -->
    </div><!-- header -->

    <div class='clear'>
    </div>

    <div id='errors'>
        {% block errors %}
        {% endblock %}
    </div>

    <div id='page'>
        {% block page %}
        {% endblock %}
    </div>

</div> <!-- bodywrapper -->
</body>
</html>

Cyber-Main/JSL_Threat_Intel_Framework/phase3_geowhois/WhoDat/pydat/pydat/templates/dnsdb.html
<div id="tab-{{set.type}}">
    {% if set.data.items %}
    <ul>
        {% for rrtype, entry in set.data.items %}
        <li><a href="#tab-{{ forloop.counter }}">{{ rrtype }}</a></li>
        {% endfor %}
    </ul>

    {% for rrtype, entry in set.data.items %}
    <div id="tab-{{ forloop.counter }}">
        <table class="dnsres">
            <thead>
            <tr>
                <th class='rrname'>rrname</th>
                <th class='rdata'>rdata</th>
                <th>First Seen</th>
                <th>Last Seen</th>
                <th class='count'>Count</th>
                <th>Actively Resolve</th>
            </tr>
            </thead>
            <tbody>
            {% for item in entry %}
            <tr>
                <td class='rrname'>
                    <a href="{% url 'pdns_rest' item.rrname %}">{{ item.rrname }}</a>
                </td>
                <td class='rdata'>
                    {% if item.rrtype == 'A' %}
                    {% for rd in item.rdata %}
                    <a href="{% url 'pdns_r_rest' " ip" rd %}">{{ rd }}</a><br>
                    {% endfor %}
                    {% else %}
                    {% for rd in item.rdata %}
                    {{ rd }}<br>
                    {% endfor %}
                    {% endif %}
                </td>
                <td>
                    {% if item.time_first %}
                    {{ item.time_first }}
                    {% else %}
                    Unknown
                    {% endif %}
                </td>
                <td>
                    {% if item.time_last %}
                    {{ item.time_last }}
                    {% else %}
                    Unknown
                    {% endif %}
                </td>
                <td class='count'>
                    {{ item.count }}
                </td>
                <td>
                    <span class="link resolve" domainName="{{ item.rrname }}">Resolve</span>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    {% endfor %}
    {% else %}
    <div id='noresults'>
        <h2>No Results Found</h2>
    </div>
    {% endif %}
</div>

Cyber-Main/JSL_Threat_Intel_Framework/phase3_geowhois/WhoDat/pydat/pydat/templates/domain.html
{% extends 'base.html' %}

{% block title %}Domain Search{% endblock %}

{% block js_constants %}
<script type="text/javascript">
        var active = 'domain';



</script>

{% endblock %}

{% block js %}
{%endblock %}

{% block searchBar %}
{% if legacy_search %}
{% include 'domain_search_form.html' %}
{% else %}
{% include 'domain_advsearch_form.html' %}
{% endif %}
{% endblock %}

{% block errors %}
{% if legacy_search %}
{% for field in domain_form %}
{% if field.errors %}
{% for error in field.errors %}
<span class='error'>
                    {{ error }}
                </span>
{% endfor %}
{% endif %}
{% endfor %}
{% else %}
{% for field in advdomain_form %}
{% if field.errors %}
{% for error in field.errors %}
<span class='error'>
                    {{ error }}
                </span>
{% endfor %}
{% endif %}
{% endfor %}
{% endif %}
{% endblock %}


{% block page%}
{% endblock %}

Cyber-Main/JSL_Threat_Intel_Framework/phase3_geowhois/WhoDat/pydat/pydat/templates/domain_results.html
{% extends 'base.html' %}

{% block title %}Domain Search{% endblock %}

{% block js_constants %}
<script type="text/javascript">
      var active = 'domain';
      var domain_url = "{% url 'ajax_domain' %}";
      var pdns_rest = "{% url 'pdns_results' %}";
    {% if legacy_search %}
      var dataTable_url = "{% url 'ajax_dataTable' %}";
      var key = "{{ key }}";
      var value = "{{ value }}";
      var low_version = {{ low_version }};
      var high_version = {{ high_version }};
    {% else %}
      var advdomains = "{% url 'advdomains' %}";
      var advDataTable_url = "{% url 'ajax_advDataTable' %}";
      var query_string = "{{ search_string }}"; 
      var query_unique = {{ query_unique }};
    {% endif %}



</script>
{% endblock %}

{% block js %}
{% if legacy_search %}
<script type="text/javascript" src="{{STATIC_URL}}/js/domain.js"></script>
{% else %}
<script type="text/javascript" src="{{STATIC_URL}}/js/domain_advanced.js"></script>
{% endif %}
{%endblock %}

{% block searchBar %}
{% if legacy_search %}
{% include 'domain_search_form.html' %}
{% else %}
{% include 'domain_advsearch_form.html' %}
{% endif %}
{% endblock %}

{% block error %}
{% endblock %}


{% block page%}
{% include 'domain_table.html' %}
{% endblock %}

Cyber-Main/JSL_Threat_Intel_Framework/phase3_geowhois/WhoDat/pydat/pydat/templates/domain_search_form.html
{% if handler == 'mongo' %}
<div id="domain" class='search_form'>
    {% if domain_form %}
    <form action="{% url 'domains' %}" method="POST">
        {% csrf_token %}
        {{ domain_form.non_field_errors }}
        <table id="domain_form">
            <tbody>
            <tr>
                <td>
                    <label for="id_key">Key:</label>
                </td>
                <td>
                    {{ domain_form.key }}
                </td>
                <td>
                    <label for="id_value">Value:</label>
                </td>
                <td>
                    {{ domain_form.value }}

                </td>
                <td>
                    <label for="id_fmt">Format:</label>
                </td>
                <td>
                    {{ domain_form.fmt }}
                </td>
            </tr>
            <tr>
                <td>
                    <label for="id_latest">Latest:</label>
                </td>
                <td>
                    {{ domain_form.latest }}
                </td>
                <td>
                    &nbsp;
                </td>
                <td>
                    &nbsp;
                </td>
            </tr>
            <tr>
                <td>
                    <div class='form_filter novis'>
                        <label for="id_filt">Filter:</label>
                    </div>
                </td>
                <td>
                    <div class='form_filter novis'>
                        {{ domain_form.filt }}
                    </div>
                </td>
                <td>
                    <div class='form_limit novis'>
                        <label for="id_limit">Limit:</label>
                    </div>
                </td>
                <td>
                    <div class='form_limit novis'>
                        {{ domain_form.limit }}
                    </div>
                </td>
                <td>
                    &nbsp;
                </td>
                <td>
                    <input type="submit" value="Search"/>
                </td>
            </tr>
            </tbody>
        </table>
    </form>
    <!--
    <div class='errors'>
        {% for field in domain_form %}
            {% if field.errors %}
                {% for error in field.errors %}
                <span class='error'>
                    {{ error }}
                </span>
                {% endfor %}
            {% endif %}
        {% endfor %}
    </div>
    -->
    {% endif %}
</div>
{% endif %}

Cyber-Main/JSL_Threat_Intel_Framework/phase3_geowhois/WhoDat/pydat/pydat/templates/domain_table.html
<table class="dnsres">
    <thead>
    <tr>
        <th>&nbsp;</th>
        <th>Name</th>
        <th>Registrant</th>
        <th>Email</th>
        <th>Created</th>
        <th>Telephone</th>
        <th>Version</th>
        {% if not legacy_search %}
        <th>Score</th>
        {% endif %}
    </tr>
    </thead>
    <tbody>
    </tbody>
</table>
<div id="dialog">
    <span id="dtext"></span>
</div>


<div id="statusDialog" title="Working ...">
    <span id="statusText">Data is being fetched from the server ... Please Wait</span>
</div>

Cyber-Main/JSL_Threat_Intel_Framework/phase3_geowhois/WhoDat/pydat/pydat/templates/error.html
{% extends 'base.html' %}

{% block title %}Error{% endblock %}

{% block js_constants %}
<script type="text/javascript">
</script>
{% endblock %}

{% block page %}
<div id='errors'>
    {{ error }}
</div>
{% endblock %}

Cyber-Main/JSL_Threat_Intel_Framework/phase3_geowhois/WhoDat/pydat/pydat/templates/pdns_form.html
<div id="pdnsf" class='search_form'>
    {% if pdns_form %}
    <form action="{% url 'pdns_results' %}" method="POST">
        {% csrf_token %}
        {{ pdns_form.pretty.as_hidden }}
        {{ pdns_form.non_field_errors }}
        <table id="pdns_form">
            <tbody>
            <tr>
                <td>
                    <label for="id_domain">Domain:</label>
                </td>
                <td>
                    {{ pdns_form.domain }}
                </td>
                <td>
                    <label for="id_absolute" title="Excludes subdomains when checked">Absolute:</label>
                </td>
                <td>
                    {{ pdns_form.absolute}}
                </td>
                <td>
                    <label for="id_rrtypes" title="DNSDB only">RRTypes:</label>
                </td>
                <td rowspan=2>
                    {{ pdns_form.rrtypes }}
                </td>
            </tr>
            <tr>
                <td>
                    <label for="id_fmt">Format:</label>
                </td>
                <td>
                    {{ pdns_form.fmt}}
                </td>
                <td>
                    <label for="id_limit" title="DNSDB only">Limit:</label>
                </td>
                <td>
                    {{ pdns_form.limit}}
                </td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            <td>
                <div class='form_filter novis'>
                    <label for="id_filter">Filter:</label>
                </div>
            </td>
            <td>
                <div class='form_filter novis'>
                    {{ pdns_form.filt }}
                </div>
            </td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>
                <input type="submit" value="Search"/>
            </td>
            <tr>
            </tr>
            </tbody>
        </table>
    </form>
    <div class='errors'>
        {% for field in pdns_form %}
        {% if field.errors %}
        {% for error in field.errors %}
                <span class='error'>
                    {{ error }}
                </span>
        {% endfor %}
        {% endif %}
        {% endfor %}
    </div>
    {% endif %}
</div>

Cyber-Main/JSL_Threat_Intel_Framework/phase3_geowhois/WhoDat/pydat/pydat/templates/pdns_table.html
<div id='pdns'>
    <ul>
        {% for set in results.sets %}
        <li><a href="#tab-{{ set.type }}">{{ set.type }}</a></li>
        {% endfor %}
    </ul>

    {% for set in results.sets %}
    {% if set.type == "DNSDB" %}
    {% include "dnsdb.html" with set=set %}
    {% elif set.type == "PassiveTotal" %}
    {% include "passivetotal.html" with set=set %}
    {% endif %}
    {% endfor %}
</div>

Cyber-Main/JSL_Threat_Intel_Framework/phase3_geowhois/WhoDat/pydat/pydat/templates/rpdns_form.html
<div id="pdnsr" class='search_form'>
    {% if pdns_r_form %}
    <form action="{% url 'pdns_r_results' %}" method="POST">
        {% csrf_token %}
        {{ pdns_r_form.pretty.as_hidden }}
        {{ pdns_r_form.non_field_errors }}
        <table id="pdnsr_form">
            <tbody>
            <tr>
                <td>
                    <label for="id_key">Type:</label>
                </td>
                <td>
                    {{ pdns_r_form.key}}
                </td>
                <td>
                    <label for="id_value">Query:</label>
                </td>
                <td>
                    {{ pdns_r_form.value}}
                </td>
                <td>
                    <div class='form_rrtypes novis'>
                        <label for="id_rrtypes" title="DNSDB only">RRTypes:</label>
                    </div>
                </td>
                <td rowspan=2>
                    <div class='form_rrtypes novis'>
                        {{ pdns_r_form.rrtypes }}
                    </div>
                </td>
                <td>
                    {# <label for="id_absolute" title="Exclude subdomains when checked">Absolute:</label>#}
                    &nbsp;
                </td>
                <td>
                    {# {{ pdns_r_form.absolute }} #}
                    &nbsp;
                </td>
            </tr>
            <tr>
                <td>
                    <label for="id_fmt">Format:</label>
                </td>
                <td>
                    {{ pdns_r_form.fmt}}
                </td>
                <td>
                    <label for="id_limit" title="DNSDB only">Limit:</label>
                </td>
                <td>
                    {{ pdns_r_form.limit}}
                </td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td>
                    <div class='form_filter novis'>
                        <label for="id_filter">Filter:</label>
                    </div>
                </td>
                <td>
                    <div class='form_filter novis'>
                        {{ pdns_r_form.filt }}
                    </div>
                </td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>
                    <input type="submit" value="Search"/>
                </td>
            </tr>
            </tbody>
        </table>
    </form>
    <div class='errors'>
        {% for field in pdns_r_form %}
        {% if field.errors %}
        {% for error in field.errors %}
                <span class='error'>
                    {{ error }}
                </span>
        {% endfor %}
        {% endif %}
        {% endfor %}
    </div>
    {% endif %}
</div>